### ISSUE TITLE
계약

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kfem#1]
## 계약
- 프로젝트 책임 (팀 두루미)
- UI 디자인(추은서, 정민수)
- 개발 (홍영택, 한운장, 이용선)
- 계약 및 운영 책임 (한운장)

## kfem 요구사항 문서

- https://docs.google.com/document/d/1z4LUNhFqgAvYCgzAlAV_KcPMQCJ4-IzaI9vXN8dV-2Y/edit#

## UI 디자인
- 테마 디자인 1세트 (나눠서 사용)
- 메인 디자인은 다르게 유지

## kfem
- wordpress to hugo로 전환해서 사용한다. 
- 전체 마이그레이션

## ekfem
- wordpress to hugo로 전환해서 사용한다.  
- 전체 마이그레이션

## 이슈
- 로그인 / 게시판

**Comment by woonjjang** [comment]
# 1. 프로젝트 이전 및 신규 개발

[테스트] hugo workshop
- 무료로 테스트를 한다. 
- 어떻게 만들어지고, 어떻게 진행될지에 대해서 확인한다. 그리고 관련된 기술을 확인하고
- marketing-theme 로 휴고 만든다.(샘플을 뭘로하고 싶은지 정해라 / 비용과 트래픽과 보안을 확인 후 진행)

[디자인] 500만원
- 중앙 / 지역 메인 디자인
- 세부화면 테마 통일

[중앙 kfem.or.kr] 1개 1500만원
- 워드프레스 to Hugo
- 데이터 마이그레이션 + 파일 마이그레이션(1개)
- 관리자 개발

[지역 ekfem.or.kr] 42개 1500만원
- 워드프레스 to hugo
- 데이터 마이그레이션 (42개)
- 관리자 개발(중앙에서 만든 것을 사용)


# 2. 프로젝트 운영비 hugo (평상시)
- 인프라 대리 관리비 (1년 10만원)
- 중앙 수정요청 대응 (1년 10만원)
- 지역 42개 수정요청 대응 (개별 사이트 1년 10만원*사이트갯수 = 420만원 / 1년)
- 지역 추가 생성비용 (50만원) - 하루 세팅 / 내용 및 기능 조정  / 인프라 세팅

# 3. 인프라 운영비 hugo -환경운동 연합 결제(평상시)
- 클라우드 플레어 R2 / 클라우드 플레어 방화벽 (유료플랜)
- 필요시 netlify 유료결제

**Comment by woonjjang** [comment]
[협의]
1. 테스트를 한다. 해 보고 아니면 종료한다. 이때 netlifycms를 사용하고 netlify identity 유료 요금제로 (40명 유저를 커버해 본다.)
2. 중앙을 해 보고, 지역을 한다. (행정적인 것은 하나로 유지될 수 있다.)

**Comment by woonjjang** [comment]
개편 대상 사이트 

- 중앙사무처 (한글 [kfem.or.kr](http://kfem.or.kr/))
- 중앙사무처 (영문 [kfem.org](http://kfem.org/))

- 지역사이트 42개 ([ekfem.or.kr](http://ekfem.or.kr/))
- 전문협력기관1 : 환경법률센터 ([ecolaw.or.kr](http://ecolaw.or.kr/))- 지역테마와 동일 혹은 더욱 간략한 레이아웃
- 전문협력기관2 : 시민방사능감시센터 ([korearadiationwatch.org](http://korearadiationwatch.org/)) - 지역테마와 동일 혹은 더욱 간략한 레이아웃
- 신규 생성 요청 지역 2개
- DB 이전 요청 지역 3개 (워드프레스 사이트는 생성되어있으나 구홈페이지 / 카페 등에서 DB를 옮겨오지 못함)

**Comment by woonjjang** [comment]
예지님과 얘기를 좀 나눴어요. 굳이 계약을 미룰 필요가 없는 상황이어서
(우리가 테스트하고 뭐 하고, 현재 서버 관련해서도 저쪽에서는 커버해 주길 원하는 상황이니깐)

마지막에 어떻게 정리되었는지 정확히 기억나지 않지만

1. 계약 -> 선금
2. UI 작업을 시작한다. (중앙 / 지역) 2-3주 - 기술적으로 어떻게 작업할지 처리를 한다. 
3. hugo로 중앙 작업을 시작한다. 
4. 캠페이너스로 지역 작업을 시작한다. 

! 한가지 캠페이너스로 갈아타면,클라우드플레어 사용은 못 하는 것으로 알고 있어요. 캠페이너의 클라우드프론트로 강제하는 정책을 쓰고 있어서

**Comment by mozodev** [comment]
공동체 사무국에서도 이거 어떻게 진행되는지 궁금해하고 있는데요...
계약을 하려면 지역을 어떻게 할 건지 합의를 해야할 듯...
일단 켄짱한테는 제가 다음주 금요일 정도까지 중앙쪽 스태틱으로 전환한 예시를 보여주겠다고 이야기는 해놓은 상태
환경운동연합에서는 지역은 그대로 워드프레스를 쓰고 싶은데 비용은 낮추고 싶어하는거 같고
사무국에서는 캠페이너스 계속 들이대려고 하는데 아마도 안 받을 듯 하고... 여기 결론을 내고 설명하고 합의해서 계약을 진행해야....

**Comment by woonjjang** [comment]
@mozodev 환경운동연합 입장은 이렇든 저렇든 알아서 맞춰주겠다고 생각한다.
그리고 현재 7월이 붕떠서 한 달이 지나갔는데, 본인들 서버도 걱정하는 것 같고,(이건 걱정말라고는 했어요.)

모조님 의견대로
지역
|- 휴고스태틱
|- 캠페이너스 게시판 

이 형태로 밀고가는게 어떨까 합니다. 그래야, 관련된 비용도 낮고 운영도 사무국에서 맡고
지혜님은 우선 믿고 맡기겠다는 것으로 보임 (좋은 안을 찾아서 좀 강력하게 미는게 좋을 듯 합니다.)

**Comment by mozodev** [comment]
그럼 일단 중앙 스태틱은 제가 삽을 뜨고 담주 화욜에 공유하고 캠페이너스 게시판은 누가해주세요~~ ㅎㅎ

**Comment by woonjjang** [comment]
[중앙] @mozodev 
- 관리자쪽을 hugo netlify cms를 사용한다. 

[지역] @woonjjang 
- 지혜님에게 캠페이너스 지역 계정으로 계정을 하나 받으라고 한다. 
- 관련되어 샘플 페이지를 보여준다. 
- 나중에 컨펌이 나면 그 캠페이너스 계정을 그대로 쓴다.

**Comment by woonjjang** [comment]
과업 범위 및 진행 프로세스
https://docs.google.com/presentation/d/1ljBHegQKxFGtme3ZBjCWB1K7vNTwzoufxkwTMvf7loc/edit#slide=id.gc6f80d1ff_0_59

**Comment by woonjjang** [comment]
계약서

https://docs.google.com/document/d/1zh3s5-33dzpxsnRSchV4Q3O7r-r876ce617OZFIWwM0/edit
