### ISSUE TITLE
크롬에서 Too many redirections

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kfem#11]
https://dash.cloudflare.com/a58368a628c50851e4b4f9b89ef2b414/ekfem.or.kr/dns
ekfem.or.kr 이런 걸 보면 모두 프록싱을 사용 중이라
아마도 맥 크롬은 투매니리다이렉션을 만나게 될 듯

>> 이유를 알 수 없지만 사용이 많은 cjcb, daejeon, jeju를 시범적으로 꺼놨음.

**Comment by mozodev** [comment]
이유는 proxy를 켜게 되면 cfl SSL을 사용할 수 있게 되고 
크롬 브라우저가 http://로 요청을 받아서 해당 서버 ssl을 사용할 수 있으면 리다이렉트를 시키는데..
아마도 헤더나 뭐 다른 방식으로 확인을... 그러나
실제로는 사용을 하지 않기 때문에 무한 리다이렉트가 되는....

프록시 켠 상태에서 ssl auto rewirte 옵션도 꺼보고 했는데 제대로 안됨.. 결국 내리는 수 밖에 없음.
SSL을 켜면 문제가 소스에 박혀있는 http:// 주소 때문에 웹사이트 깨진 것 처럼 보여서 
걍 http://로 써야함...
