### ISSUE TITLE
post-detail (kfem)

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kfem#13]
http://kfem.or.kr/?p=229272

썸네일형 게시판과 리스트형 게시판에서 클릭하면 보이는 동일한 세부 레이아웃이 필요합니다. 
전화통화로 요청하려던 것

대표썸네일
제목
날짜
작성자

본문(html)

첨부파일

**Comment by calvin-design** [comment]
작업 완료했습니다
https://www.figma.com/file/oMFzOskvZ1LPBbHnbj7dMx/Kfem_?node-id=966%3A1559&t=1HdSnucOQOIXi4Vk-1
