### ISSUE TITLE
UI 디자인 -> 테마 및 메인 시안(9월)

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kfem#3]
@calvin-design  kfem / ekfem 메인 및 세부 디자인을 구성한다.

**Comment by woonjjang** [comment]
https://github.com/team-durumi/kfem/issues/6#issuecomment-1230390276

캠페이너스와 휴고 header 스타일 검수 요청

**Comment by woonjjang** [comment]
제가 이해하는 디자인 방향 까지만, 오늘 회의에서 질문을 많이 해주세요 ~

1. https://kfem.or.kr/ (중앙) cjcb,ekfem.or.kr jeju.ekfem.or.kr (지역 - 총 50여개가 있음)
2. 엑스트라 사이트
<img width="1115" alt="Screen Shot 2022-09-01 at 7 49 22 AM" src="https://user-images.githubusercontent.com/6022883/187798537-fb2e66bb-a210-496e-a33f-b12675e43677.png">

 => 하나의 테마를 활용해서 컨텐츠가 다를 때 해당 영역이 다른 디자인으로 보이고, 다양성을 줄 수 있어야 할 것 같아요. 
예전에는 kfem 과 ekfem이 모두 워드프레스 테마를 만들어서 같이 썼으니, 개념상으로는 워드프레스 테마를 휴고 테마로 바꾸는 작업입니다. 

섹션 영역이 좁은 테마로 기획되어 있었고, 전체적으로 좁고 그렇죠. 

구글 드라이브에 자료들 전부 올리고 있으니, 그것들 훑어봐도 좋을 것 같아요. 
메인 레이아웃은 봤을 것으로 보이고

다 비슷해 보이겠지만 "환경"이 붙은 시민단체중 오래된 곳이기 때문에 그곳들을 리서치하고 차별성을 갖는게 중요할 수 있어요. 

서울환경연합 (같은 것 같지만 다른) https://seoulkfem.or.kr/
환경재단 http://www.greenfund.org/

이런 곳들과 차별성이 필요해 보입니다. 

이따 회의하면서 또 공유할께요.

**Comment by woonjjang** [comment]
디자인 컨셉
키워드 : 모던, 군더더기 없는, 세련된, 깔끔한, 편안한
톤앤매너 : 전반적으로 무채색 혹은 채도가 낮은 톤으로 구성된 베이스에 그린이 포인트 칼라로 들어가는 디자인
주요 칼라 : 블랙, 화이트, 옅은 베이지, 옅은 회색, 짙은 회색 등. 포인트 그린은 촌스럽지 않은 녀석을 잘 골라주세요 ㅎㅎ

선호 : 
- 적절하게 얇은 선 요소를 넣으면 세련돼 보이더라고요.
- 적절한 애니메이션
- 데스크탑, 태블릿, 모바일에서 모두 보기 좋은 디자인. (활동가들은 홈페이지 운영을 주로 데스크탑 환경으로 하기 때문에 데스크탑 화면이 보기 좋아야 호응도가 좋을 거예요.)

불호 :
- 형광끼 있는 칼라
- 다소 극단적인 디자인
- 너무 큰 글씨와 요소들
- 컨셉에 치중한 나머지 가독성이 떨어지는 디자인

https://www.behance.net/gallery/134375991/ALKI-Website
https://www.behance.net/gallery/148441171/Kitc

**Comment by woonjjang** [comment]
참고
서울환경운동연합 https://seoulkfem.or.kr/
녹색연합 https://www.greenkorea.org/
환경재단 http://www.greenfund.org/
그린피스코리아 https://www.greenpeace.org/korea/
그린피스 아프리카 https://www.greenpeace.org/africa/en/
국립공원 탐방아카이브 https://www.knps.or.kr/archive/s/site/page/main

**Comment by woonjjang** [comment]
@calvin-design https://www.behance.net/gallery/134375991/ALKI-Website 첫 번째 레퍼런스는 현재 사진 quallity로 나올 수 있는 버전인가 싶긴 하네요. ㅎㅎ

**Comment by woonjjang** [comment]
이슈 이름을 시안으로 변경했습니다.

**Comment by calvin-design** [comment]
> @calvin-design https://www.behance.net/gallery/134375991/ALKI-Website 첫 번째 레퍼런스는 현재 사진 quallity로 나올 수 있는 버전인가 싶긴 하네요. ㅎㅎ

ㅎㅎ 어디서도 나오기 힘든 버전이쥬

**Comment by woonjjang** [comment]
https://tailwindui.com/templates
구현쪽에서는 이쪽도 확인하고 있으니, 시안 잡을 때 좀 봐주시면 좋을 듯 

모던한 느낌을 더 주기위해서 고객에게 환경운동연합 미디어 사진을 좀 받아서, 편집해서 넣는게 좋을지도

**Comment by woonjjang** [comment]
좀 늦었지만 시안 종료. 테마에 집중해서 힘 내세요 !!
