### ISSUE TITLE
kfem.or.kr xml 마이그레이션( wordpress to hugo)

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kfem#5]
깔끔하게는 안 되겠지만 쉬운 이동방법을 찾아보자면.

**Comment by woonjjang** [comment]
## 지난주 공유처럼 wordpress 복원해서 진행하는 것과 크게 다른 것은 없으나
- 깔끔한 body 텍스트를 뽑는 방법이 없을까.
- ww 프로젝트가 압박이 있이나 이것 저것 해 보다가.

## wordpress xml 은 포맷이 잘 정리되어 있으니 잘 뽑아지지 않을까 했음. 
![Screen Shot 2022-10-24 at 11 19 35 PM](https://user-images.githubusercontent.com/6022883/197556687-988b1970-4c31-41af-a4cc-20d386e535ae.png)


## 변환과정
- 3개 카테고리를 찍어서 xml 변환을 하고
- https://wpxss.com/wp-content/convert-wordpress-to-markdown/ 컨버터에서 해당 xml을 export.xml로 변환한 이후에
- parser 가 썬이 만들어놓은 예전 ruby 스크립트처럼 md file을 생성
- 해당 md 파일들 본문에 첨부파일 구조가 잘 잡혀 있어서 body 부분이 괜찮아 보임. 

## 스크립트 해결은 못 했는데
- 좀 만지면, 썸네일을 잡아주거나, 다른 옵션들도 넣을 수 있지 않을까...
- 공지사항과 보도자료는 parsing error가 발생하는 듯

## 구글 드라이브 backup 폴더에 생성한 md 파일 옮겨놨습니다. 

![Screen Shot 2022-10-24 at 11 50 12 PM](https://user-images.githubusercontent.com/6022883/197557728-adfae614-e60c-4e0c-9856-164b94c54d13.png)

**Comment by woonjjang** [comment]
womenandwar에서는 1차로 해결할 수 있을 것으로 보임. 
- 기존사이트에서도 썸네일 관리가 되지 않았음. 
- 생각보다 몇 개 없음.

**Comment by mozodev** [comment]
https://github.com/lonekorean/wordpress-export-to-markdown/blob/master/src/translator.js#L59
여기 보니 본문 html 다루기 위해서 뭔가 많이 하네요 ㅎㅎ
https://github.com/c0b41/htmltidy2
https://github.com/apostrophecms/sanitize-html
이런 거 써써 좀 정리해주면 에러가 줄어들지 않을까 합니다 ㅎ
