### ISSUE TITLE
지역 관련 이슈

### ISSUE THREAD

**Issue by mozodev** [team-durumi/kfem#9]
- [ ] ~~http://ekfem.or.kr 접근 안됨  `cloudflare error 524`~~

> CFL이 웹서버에 연결했지만 100초 동안 응답이 없었다.
nginx 설정 확인해보니 사용하지 않는 가상호스트 설정이 두 개가 있음...

그런데 여기는 원래 두루미가 처음 유지보수 맡았을 때부터 화면이 없었음....

- [x] 지역 워드프레스 글쓰기 화면이 block editor로 변경됐다. classic editor를 사용하고 싶다.

> 이건 확인해봐야겠지만 누군가 코어 업그레이드를 시도한 것으로 보임...
cloudflare도 그렇고 누군가 만지고 있는것 같다. 만진 놈이 해결해야함 ㅎㅎ

9월 8일 오후 1시 21분 코어 파일이 마지막 변경된 것으로 확인... 누군가 버튼을 눌렀... ㅎ

**Comment by h2dj** [comment]
* 한 달 전쯤 접속한 적이 있다고 함
* 클래식 에디터가 만료됐기에 워드프레스 코어가 업그레이드 된 거면 다운그레이드 하거나, 클래식 에디터 플러그인을 설치해서 써야 할 것 같음
* 일단 ekfem.or.kr 이 안 뜨는 이유를 찾아야 할 것 같음..

**Comment by mozodev** [comment]
> 네, 지역사이트 클래식 에디터 잘 되네요. 아직도 ekfem.or.kr은 접속이 안되는데 급한 것은 아니니 천천히 봐주셔요.

> 이번 상황을 확인해보니, 
> 워드프레스 업데이트는 수원환경연 활동가가 추석 전에 수원 관리자 페이지에서 클릭한 게 이 사단이 난 걸로 파악됩니다. 왜 수원 뿐만 아니라 전체 지역 페이지에서 업데이트가 되었는지는 모르겠는데… 아무래도 멀티사이트라 연동되어있는 모양입니다.

> 연휴 전 편집기가 바꼈는데 지역에서 어제 저녁에서야 저는 확인한 거고요.. 

> 고생해주셔서 감사합니다. 😭

**Comment by mozodev** [comment]
@h2dj 
원인 확인되기 전에 카톡에다 한줄 남기고 작업 직접 하지 않으셨으면 좋겠습니다.
이게 원인이 활동가가 코어 업데이트한거면 그 에디터 바뀐 것도 원래버전으로 되돌리면 해결될덴테요...
상의도 없이 작업하시려면 전부 다 하세요. 괜히 일만 늘어나잖아요? ㅎ

**Comment by mozodev** [comment]
~~언제까지? 금요일 전까지
왜? 로컬 환경에서 테스트하고 확인해야하니까~~

- [x] ~~S3에서 예전 백업 파일 확보~~
- [ ] ~~classic editor 플러그인 비활성화 및 삭제~~
- [ ] ~~core 원복~~

**Comment by mozodev** [comment]
에디터 문제는 해결했고 네트워크 관리자 로그인 안되는 것은 그냥 수동으로 관리하는 것으로 하고 닫습니다.
